"""Generate ASCII menu glyphs from the bundled OFL Roboto font; requires Pillow."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
root = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(str(root/'assets/fonts/Roboto.ttf'), 18*4)
data, offsets, widths = [], [], []
for c in map(chr, range(32,127)):
    width = max(2, round(font.getlength(c)/4)+1)
    tile = Image.new('L', (width*4, 24*4))
    ImageDraw.Draw(tile).text((0,19*4), c, font=font, fill=255, anchor='ls')
    values = [(v*15+127)//255 for v in tile.resize((width,24), Image.Resampling.LANCZOS).getdata()]
    offsets.append(len(data)); widths.append(width)
    data.extend((values[i]<<4)|values[i+1] for i in range(0,len(values),2))
lines = ['#pragma once','#include <stdint.h>','// Generated by tools/generate_menu_font.py; Roboto SIL OFL 1.1.', 'namespace MenuFont {', 'constexpr int Height=24;', 'static const uint16_t Offsets[] = {'+','.join(map(str,offsets))+'};', 'static const uint8_t Widths[] = {'+','.join(map(str,widths))+'};', 'static const uint8_t Coverage[] = {']
lines += ['  '+','.join(map(str,data[i:i+32]))+',' for i in range(0,len(data),32)]
(root/'hardware/MenuFont.h').write_text('\n'.join(lines+['};','}'])+'\n')
