"""Pack the generated stone photograph for the LCD. Requires Pillow.
The source image remains unchanged; conversion only fits the device size and
quantizes to RGB565. Display dimming is performed by the C++ presentation layer.
"""
from pathlib import Path
from PIL import Image, ImageOps
ROOT = Path(__file__).resolve().parents[1]
image = ImageOps.fit(Image.open(ROOT/'assets/backgrounds/stones-source.png').convert('RGB'),
                    (280,240), method=Image.Resampling.LANCZOS)
image.save(ROOT/'assets/backgrounds/stones-lcd.png')
pixels = [((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in image.getdata()]
lines = ['#pragma once','#include <stdint.h>',
         '// Generated by tools/generate_stone_background.py; pixels reside in flash.',
         'namespace StoneBackground {','constexpr int Width = 280, Height = 240;',
         'static const uint16_t Pixels[] = {']
for i in range(0,len(pixels),20):
    lines.append('  '+','.join(f'0x{p:04x}' for p in pixels[i:i+20])+',')
lines += ['};','}']
(ROOT/'hardware/StoneBackground.h').write_text('\n'.join(lines)+'\n')
