"""Generate the firmware's 4-bit Roboto digit masks. Requires Pillow.
Source: assets/fonts/Roboto.ttf (SIL OFL 1.1; see assets/fonts/OFL.txt).
Run from any directory: python3 tools/generate_timer_font.py
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(str(ROOT / 'assets/fonts/Roboto.ttf'), 60 * 4)
axes = font.get_variation_axes()
font.set_variation_by_axes([350 if axis['name'] == b'Weight' else axis['default'] for axis in axes])
data = []
offsets = []
for char in '0123456789:':
    width = 14 if char == ':' else 36
    tile = Image.new('L', (width * 4, 58 * 4))
    draw = ImageDraw.Draw(tile)
    x = (width * 4 - font.getlength(char)) / 2
    draw.text((x, 50 * 4), char, font=font, fill=255, anchor='ls')
    tile = tile.resize((width, 58), Image.Resampling.LANCZOS)
    pixels = [(value * 15 + 127) // 255 for value in tile.getdata()]
    offsets.append(len(data))
    data.extend((pixels[i] << 4) | pixels[i+1] for i in range(0, len(pixels), 2))
lines = ['#pragma once', '#include <stdint.h>',
         '// Generated by tools/generate_timer_font.py. Roboto, SIL OFL 1.1.',
         'namespace TimerFont {', 'constexpr int Height = 58, DigitWidth = 36, ColonWidth = 14, Gap = 4;',
         'static const uint16_t Offsets[] = {' + ','.join(map(str, offsets)) + '};',
         'static const uint8_t Coverage[] = {']
for i in range(0, len(data), 24):
    lines.append('  ' + ','.join(f'0x{v:02x}' for v in data[i:i+24]) + ',')
lines += ['};', '}']
(ROOT / 'hardware/TimerFont.h').write_text('\n'.join(lines) + '\n')
